---
name: Tests

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        kubernetes:
        - v1.24.15
        - v1.25.11
        - v1.26.6
        - v1.27.3
        - v1.28.0

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup Cache for Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build source files
      run: go build ./...

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ matrix.kubernetes }}

    - name: Create KinD cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.17.0
        node_image: kindest/node:${{ matrix.kubernetes }}
        cluster_name: kind
        wait: 120s

    - name: Install Tekton
      run: hack/install-tekton.sh

    - name: Install Shipwright
      run: hack/install-shipwright.sh

    - name: Run Tests
      run: |
        go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
        make test

    - name: Upload Code Coverage Profile
      uses: codecov/codecov-action@v3
      with:
        threshold: 2%
        files: unit.coverprofile
        flags: unittests
        fail_ci_if_error: true
        verbose: false
